### ISSUE TITLE
CSS Styles not working out of the box?

### ISSUE THREAD

**Issue by asishallab** [excid3/simple_calendar#104]
Following the installation guide and added simple_calendar into a latest clone of 
https://github.com/RailsApps/rails-bootstrap
in the welcome ERB using

<%= month_calendar do |date| %>
  <%= date %>
<% end %>

The calendar looks like this:
![image](https://cloud.githubusercontent.com/assets/575529/9754992/71c09d56-56ce-11e5-968a-076cdc4134c5.png)

What am I doing wrong?

Cheers!

**Comment by excid3** [comment]
Hey @asishallab! So simple_calendar doesn't actually come with CSS (that's why it's simple) but I think you make a good point in that I should probably include some optional styles. 

Right now I just apply the basic table and table-striped css from Bootstrap as a default which gets you the general layout. You'll have to style each piece separately though (for now).

I'm going to leave this ticket open and we can add some default CSS that applies to the table to make it a little prettier by default.

**Comment by asishallab** [comment]
Dear @excid3, thank you for clearing that up. I at least would be very grateful for default styles that make the calendar look like it does in the screenshot. Including Bootstrap I got pretty close with table-bordered and table-striped, but the days still look somewhat uglier than seen in the provided screenshot. 
Anyhow, I think you did a very good job with simple_calendar. It really does what it promises. Thank you for that.

**Comment by jgrannas** [comment]
@excid3 I found this issue posting when i browsed the src and found no css files. It would be nice if you could just post up your stylesheet you used in the screenshot or include it as _default or something in the gem, then allow users to modify what they need.

**Comment by excid3** [comment]
Thanks guys! I just pushed up a new release (2.0.3) that includes a stylesheet that you can use. Just import it with `*= require simple_calendar` and you should be set!

**Comment by jeremy-jouffroy** [comment]
@askarhu with SCSS do 
`@import "simple_calendar"; `
instead of 
`*= require simple_calendar`

**Comment by lukyans** [comment]
How to include styles with webpacker in rails 6?

**Comment by od-c0d3r** [comment]
@lukyans did you find out ?
