### ISSUE TITLE
Feature request: extra week column with code proc

### ISSUE THREAD

**Issue by cdekker** [excid3/simple_calendar#128]
I am running an older version of simple_calendar (0.1.8) in a legacy project that I am trying to get up to date.

Back in the day I hacked some extra functionality into my local copy that allowed me to render content for each week in the (month) calendar in an extra column on the left side.

See these images for example: http://imgur.com/a/JeWJf

Is it possible to get this kind of functionality in the latest version? Would love to be able to update and use the new functionality that this gem has by now.

I had created it so that you could supply an extra block such as:

      <%= calendar @events, {:start_day => :monday, :week => 'wk', :week_proc => lambda { |d| employee_availability_calendar_week_proc(d) }} do |event| %>
          <%= employee_availability_calendar_event event %>
      <% end %>

to be able to dynamically render content for the different weeks.

**Comment by excid3** [comment]
Yeah, this should definitely be doable in the new version. I've set it up so that you can just install the HTML templates and customize them. Since it slices in 7 day chunks, you can just insert your `<td>` column into the loop for each week and that will do the trick!

You will have to upgrade to the latest version of 2.0 so that you can get those templates and have them installed.
