### ISSUE TITLE
First day of week defaulting to Monday

### ISSUE THREAD

**Issue by fizgig** [excid3/simple_calendar#136]
rails 3.2.14

this is in application.rb and does not change it:
`config.beginning_of_week = :sunday `

I tried this in application_controller.rb
```
class ApplicationController < ActionController::Base
  before_filter :set_beginning_of_week, if: :user_signed_in?

  private

    def set_beginning_of_week
      Date.beginning_of_week = :sunday
    end
```

and get this error: 
NoMethodError at /email_dates/calendar
undefined method `beginning_of_week=' for Date:Class

Sorry if this isn't a bug, but I don't know where else to ask the question, and the documentation appears to be down at http://apidock.com/rails/Date/beginning_of_week.

**Comment by excid3** [comment]
I think this might be that the ability to set the beginning_of_week was only added in Rails 4 which is why you get the `NoMethodError`. I can't get API Dock to load in order to verify that, but I'm pretty sure that's the case.

I'm not sure if it's easy to backport that Date stuff to Rails 3.2, if that's the case. Might want to look into that. Otherwise your best option would be to override the Calendar classes from simple calendar to call the method like `beginning_of_week(:sunday)`.

**Comment by fizgig** [comment]
Thanks for the help, no idea if this is the right way to do it (I'm more of a iOS/Android/PHP/.Net guy helping someone out) but I kludged this together, I made a file called datefix.rb in the initializers folder with this code. 
```
module SimpleCalendar
  class MonthCalendar < SimpleCalendar::Calendar
    private
      def date_range
        week_start_day = :sunday #options.fetch(:week_start_day, :sunday)
        beginning_of_week = start_date.beginning_of_month.beginning_of_week(week_start_day)
        end_of_week  = start_date.end_of_month.end_of_week(week_start_day)
        (beginning_of_week..end_of_week).to_a
      end
  end
end
```

 I left the call to options commented just in case it's ever upgraded

**Comment by excid3** [comment]
Pretty much exactly what I was thinking. That should do the trick nicely @fizgig. Now you can consider yourself a Ruby guy as well. ;)
