### ISSUE TITLE
Pre-written view for calendar screenshot in the readme

### ISSUE THREAD

**Issue by zeeshan-m** [excid3/simple_calendar#140]
Is there a pre-built/written view to output the calendar looking like the one in the readme (below)?

![image](https://cloud.githubusercontent.com/assets/5633907/15951208/6a62d298-2e84-11e6-9aac-dee7d82f4ad7.png)

Just thought i'd make ask before writing our own view. By generating the built in views through the gem generators the calendar looks:

![image](https://cloud.githubusercontent.com/assets/5633907/15951263/b75e6ac6-2e84-11e6-9bac-1a90699207c8.png)

**Comment by excid3** [comment]
The original screenshot is from Bootstrap 2.0 so it's a bit older but that was the table them there. I also gave the TDs a min-height so that they would show up a bit more square along with a width on the table.

You can add those styles to your stylesheet and you should be pretty much have a clone of the original.

**Comment by zeeshan-m** [comment]
Sorry, I guess my question was more regarding the info on the right, but after reading through the docs a bit more I've realized it's just simple view overrides/extensions. Sorry for the dumb question and thanks for your response!

**Comment by excid3** [comment]
Oh, that's just printing out the list of events like your normal index page. 👍
