### ISSUE TITLE
Weeks scaling to month instead of year

### ISSUE THREAD

**Issue by wgailey24** [excid3/simple_calendar#153]
Week 5 changes based on what month you're coming from and never gives the full 7 days.
![weektomonthproblem](https://cloud.githubusercontent.com/assets/15274481/20722192/a51caa30-b633-11e6-8ec2-d2fcc189872c.jpeg)

**Comment by excid3** [comment]
I'm not quite sure I understand what's wrong. Are you saying the css classes it adds are off? This calendar looks correct.

They all match up correctly to the calendar
![calendar 2017](https://www.vertex42.com/calendars/images/2017-calendar-with-holidays.png)

**Comment by wgailey24** [comment]
yeah that could be css, notice how i have week 5 twice there and they do not match because different days are greyed out, yes they would match up to that calendar because it breaks the weeks up into months i.e. year>month>week instead of year>week
weeks of the year not weeks of the month of the year.

**Comment by excid3** [comment]
What class it it that you're styling against?

I'm still not quite sure I understand your explanation of year>month>week.

**Comment by wgailey** [comment]
Ohh it's not my css applying to that, I mean within the gem, you already know the all css I have applying to the calendar. I mean the weeks are grey ing out days based on when the month ends instead of just the year and when the month starts/ends depends on which month you're coming from. Basically the grayed out days in week 5, it would be better if they wernt greyed unless there's a year break.
Best,
Will 
On Nov 29, 2016 3:44 PM, Chris Oliver <notifications@github.com> wrote:What class it it that you're styling against?
I'm still not quite sure I understand your explanation of year>month>week.

**Comment by excid3** [comment]
Still not sure what you mean. The CSS class for "current-month" and "next-month" is the only thing that changes in the calendar, which you must be styling against in order to get those grayed out. The calendar is rendering fine, it's just that the CSS class changes going to and from the next month. 

Those classes probably shouldn't be included in the week calendar because you're not looking at a "month" and there's no real good way to determine which is the current, next, or previous month.

**Comment by excid3** [comment]
If you inspect the html you'll see that class current-month and prev-month flip flops when you go forwards/backwards.

Does that make any sense?

**Comment by wgailey** [comment]
Yeah that makes perfect sense but I'm pretty sure I don't have any other css applying to it, I'll check again tomarrow morning though.
On Nov 29, 2016 7:26 PM, Chris Oliver <notifications@github.com> wrote:If you inspect the html you'll see that class current-month and prev-month flip flops when you go forwards/backwards.
Does that make any sense?

**Comment by wgailey** [comment]
Yeah, chris
No css applying to grey out days. And this is last little issue.
Best,
Will 
On Nov 29, 2016 7:33 PM, William Gailey <wgailey24@yahoo.com> wrote:Yeah that makes perfect sense but I'm pretty sure I don't have any other css applying to it, I'll check again tomarrow morning though.
On Nov 29, 2016 7:26 PM, Chris Oliver <notifications@github.com> wrote:If you inspect the html you'll see that class current-month and prev-month flip flops when you go forwards/backwards.
Does that make any sense?

**Comment by excid3** [comment]
Hmmm, are you using the default simple_calendar css file? I believe it marks next/prev month as gray background. You could remove that.

**Comment by wgailey** [comment]
Looking at it for the purposes I'm needing it for, I guess the greyed out is fine.
Quick question though; was thw fix for week 0 ever pushed up to ruby gems?
On Nov 30, 2016 1:43 PM, Chris Oliver <notifications@github.com> wrote:Hmmm, are you using the default simple_calendar css file? I believe it marks next/prev month as gray background. You could remove that.

**Comment by excid3** [comment]
Not yet, wanted to confirm that it was fixed first. I will publish that now.

You definitely have CSS coming from somewhere, whether it's the simple_calendar.css or something else, there's something defined to make those dates gray.

**Comment by excid3** [comment]
Gem is published.

**Comment by MarcusPetri** [comment]
@excid3 the annual view is no longer available in the gem?

like your comment: https://github.com/excid3/simple_calendar/issues/153#issuecomment-263674347

**Comment by excid3** [comment]
@MarcusPetri That was never part of the gem. You just render 12 month calendars and specify the start_date for each month.
