### ISSUE TITLE
Editing just one of the recurring events

### ISSUE THREAD

**Issue by jeffwolfram** [excid3/simple_calendar#177]
I watched you railscast on adding recurring events to the simple calendar. It was great and thanks so much for doing that video. I was wondering how I would go about making it so I can edit just one event in the set of recurring events. As it is now, when you make an edit, you edit them all.

**Comment by excid3** [comment]
It's been a while since I've done work on recurring events, but the idea is pretty simple when you want to make an exception for this.

1. Add an exception to the recurring event to remove the specific date.
2. Create a new separate event for that date, which you can prepopulate with the same attributes as the recurring one, without the recurring flags.

You'd want to do both of those together at the same time so you'll probably want to add a UI flow when you edit the event to choose whether you're editing the series or just this single event so that you can pass that to the server and choose the appropriate update process.

**Comment by jeffwolfram** [comment]
Cool thanks so much and I am really liking your tutorials!

**Comment by excid3** [comment]
Thanks man! Good luck and let me know how it goes!
