### ISSUE TITLE
Infinite Scrolling Calendar?

### ISSUE THREAD

**Issue by sylverfyst** [excid3/simple_calendar#187]
If I wanted to make a month calendar that kept cycling through the months as you scrolled down, how do you suggest going about doing that?  

I thought about appending a month to the calendar with ajax on scroll, but that tended to be finicky and would fire multiple times.  

I'd rather not load the whole thing if avoidable because there's around 18 months worth of events to load and that would likely bog down performance.

Any thoughts? Thanks in advance.

**Comment by excid3** [comment]
Hmm, that's a good question. I mean, you'd want to load definitely the current and previous and next months so that your calendar was tall enough to fill the screen and you had the next month ready to go.

It should be the same as infinite scroll pagination, when you scroll down you fire the event to load the next page of results (in this case the next month calendar) and append that. Each time you'd grab a calendar, you'd grab the events that were inside that month and pass them into the render so you're only loading a month's worth of events at a time.

If you're having trouble with the scroll firing multiple times, you should check to see what the infinite scroll pagination does to address that. It's basically the same exact solution. I'm curious what you find out about this, would be a really neat feature.
