### ISSUE TITLE
I want to help out. Where should I start?

### ISSUE THREAD

**Issue by pmichaeljones** [excid3/simple_calendar#212]
Hi Chris,
I'm an active user of simple_calendar and I want to start contributing. It'll be a good way for me to get my feet wet in the world of open source development. Are there any features that you'd like to see added that I can start building? 

Thanks,
Patrick

**Comment by excid3** [comment]
Hey Patrick! Would love to have your help contributing. It's been a while since I've worked on this so I don't remember exactly what needs work. It's mostly complete, so there's not a whole lot that it needs. 

I guess a good place to start would be reviewing the issues and PRs and see what those have to say.
