### ISSUE TITLE
month_calendar generates date strings in <td>'s instead of expected display.

### ISSUE THREAD

**Issue by grahamsutt12** [excid3/simple_calendar#75]
![screen shot 2015-03-04 at 2 52 27 pm](https://cloud.githubusercontent.com/assets/7832785/6491606/60396b8a-c27c-11e4-9975-ac1665ab7172.png)

I installed the gem and ran `bundle install` as advised in the README. 

When I ran this using HAML:
```haml
= month_calendar do |date|`
   = date
```
I ended up with the above screenshot. Am I possibly missing a CSS file of some sort or is this an error?

**Comment by excid3** [comment]
Check your HTML and you should see those are all in `<td>` tags. If you're using bootstrap, it should add the class of `table` to the calendar so it shows better by default. Otherwise you can style it yourself. It's got quite a few CSS classes it applies automatically but the main ones would be setting your widths and minimum heights on the calendar days.
